name: C CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: make test
      run: make test
